// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnBReport.DAL.Models;

public partial class MonthlySaleHeader
{
    public int Id { get; set; }

    public int? Year { get; set; }

    public int Month { get; set; }

    public string StoreCode { get; set; }

    /// <summary>
    /// Tong so ban ( copy tu ben Store)
    /// </summary>
    public int? Tables { get; set; }

    /// <summary>
    /// Nhap vao tong so khach
    /// </summary>
    public int Tc { get; set; }

    /// <summary>
    /// Tong so sale tinh tu ben detail qua
    /// </summary>
    public decimal Sales { get; set; }

    /// <summary>
    /// Tong so COS tinh tu ben detail qua
    /// </summary>
    public decimal? Cos { get; set; }

    /// <summary>
    /// Sales-COS
    /// </summary>
    public decimal TotalMargin { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<MonthlySale> MonthlySales { get; set; } = new List<MonthlySale>();
}