// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnBReport.DAL.Models;

public partial class MonthlySale
{
    public Guid Id { get; set; }

    public int? ParentId { get; set; }

    /// <summary>
    /// MenuItem code
    /// </summary>
    public string ProductCode { get; set; }

    /// <summary>
    /// Copy
    /// </summary>
    public string ProductName { get; set; }

    /// <summary>
    /// Copy
    /// </summary>
    public string Unit { get; set; }

    /// <summary>
    /// Copy
    /// </summary>
    public string GroupCode { get; set; }

    /// <summary>
    /// Thay doi theo thang, copy tu bang Master
    /// </summary>
    public decimal Cosprice { get; set; }

    /// <summary>
    /// Thay doi theo thang, copy tu bang Master
    /// </summary>
    public decimal SellingPrice { get; set; }

    /// <summary>
    /// Selling-COS
    /// </summary>
    public decimal Margin { get; set; }

    public int SoldQuantity { get; set; }

    public decimal? CosPercentage { get; set; }

    public decimal? SaleMixPercentage { get; set; }

    public decimal? MarginMixPercentage { get; set; }

    public decimal? ProductMixPercentage { get; set; }

    public decimal? TcTable { get; set; }

    public decimal? Per100Tc { get; set; }

    public decimal? Per100Quality { get; set; }

    public decimal? Per100Selling { get; set; }

    public string Popularity { get; set; }

    public string Profitability { get; set; }

    public string ItemClass { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public virtual MonthlySaleHeader Parent { get; set; }
}