// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FnBReport.DAL.Models;

public partial class POSReportContext : DbContext
{
    public POSReportContext(DbContextOptions<POSReportContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MonthlySale> MonthlySales { get; set; }

    public virtual DbSet<MonthlySaleHeader> MonthlySaleHeaders { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductGroup> ProductGroups { get; set; }

    public virtual DbSet<Store> Stores { get; set; }

    public virtual DbSet<StoreGroup> StoreGroups { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MonthlySale>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_MonthlySale_1");

            entity.ToTable("MonthlySale");

            entity.HasIndex(e => e.ProductCode, "IX_MonthlySale").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CosPercentage)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("COS_Percentage");
            entity.Property(e => e.Cosprice)
                .HasComment("Thay doi theo thang, copy tu bang Master")
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("COSPrice");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySale_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySale_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.GroupCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("alacarte")
                .HasComment("Copy")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySale_Type");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySale_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySale_IsDeleted");
            entity.Property(e => e.ItemClass)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Margin)
                .HasComment("Selling-COS")
                .HasColumnType("decimal(18, 3)");
            entity.Property(e => e.MarginMixPercentage)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("MarginMix_Percentage");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySale_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySale_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Per100Quality).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Per100Selling).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Per100Tc)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("Per100TC");
            entity.Property(e => e.Popularity)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("MenuItem code");
            entity.Property(e => e.ProductMixPercentage)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("ProductMix_Percentage");
            entity.Property(e => e.ProductName)
                .HasMaxLength(250)
                .HasComment("Copy");
            entity.Property(e => e.Profitability)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SaleMixPercentage)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("SaleMix_Percentage");
            entity.Property(e => e.SellingPrice)
                .HasComment("Thay doi theo thang, copy tu bang Master")
                .HasColumnType("decimal(18, 3)");
            entity.Property(e => e.TcTable)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("TC_Table");
            entity.Property(e => e.Unit)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Copy");

            entity.HasOne(d => d.Parent).WithMany(p => p.MonthlySales)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_MonthlySale_MonthlySaleHeader");
        });

        modelBuilder.Entity<MonthlySaleHeader>(entity =>
        {
            entity.ToTable("MonthlySaleHeader");

            entity.Property(e => e.Cos)
                .HasComment("Tong so COS tinh tu ben detail qua")
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("COS");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySaleHeader_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySaleHeader_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySaleHeader_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySaleHeader_IsDeleted");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySaleHeader_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_MonthlySaleHeader_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Sales)
                .HasComment("Tong so sale tinh tu ben detail qua")
                .HasColumnType("decimal(18, 3)");
            entity.Property(e => e.StoreCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Tables).HasComment("Tong so ban ( copy tu ben Store)");
            entity.Property(e => e.Tc)
                .HasComment("Nhap vao tong so khach")
                .HasColumnName("TC");
            entity.Property(e => e.TotalMargin)
                .HasComment("Sales-COS")
                .HasColumnType("decimal(18, 3)");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Product");

            entity.HasIndex(e => e.Number, "IX_Product").IsUnique();

            entity.Property(e => e.Cosprice)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("COSPrice");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Product_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Product_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.GroupCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("alacarte")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Product_Type");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Product_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Product_IsDeleted");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Product_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Product_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(250);
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SellingPrice).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Unit)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.GroupCodeNavigation).WithMany(p => p.Products)
                .HasPrincipalKey(p => p.Number)
                .HasForeignKey(d => d.GroupCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Product_ProductGroup");
        });

        modelBuilder.Entity<ProductGroup>(entity =>
        {
            entity.ToTable("ProductGroup");

            entity.HasIndex(e => e.Number, "IX_ProductGroup").IsUnique();

            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(250)
                .HasDefaultValue("alacarte")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductGroup_Type");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductGroup_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductGroup_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductGroup_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_ProductGroup_IsDeleted");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductGroup_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductGroup_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(250);
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Store>(entity =>
        {
            entity.ToTable("Store");

            entity.HasIndex(e => e.Number, "IX_Store").IsUnique();

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Store_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Store_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.GroupId).HasComment("Nhom cac kho lai");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Store_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Store_IsDeleted");
            entity.Property(e => e.MinMenuSelling)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("MIN_Menu_Selling");
            entity.Property(e => e.MinSalesContribution)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("MIN_Sales_Contribution");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Store_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Store_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(250);
            entity.Property(e => e.NumOfTables).HasColumnType("decimal(18, 3)");
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Group).WithMany(p => p.Stores)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Store_StoreGroup");
        });

        modelBuilder.Entity<StoreGroup>(entity =>
        {
            entity.ToTable("StoreGroup");

            entity.HasIndex(e => e.Number, "IX_StoreGroup").IsUnique();

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreGroup_CreatedBy");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreGroup_CreatedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreGroup_IsActive");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_StoreGroup_IsDeleted");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("System")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreGroup_ModifiedBy");
            entity.Property(e => e.ModifiedOn)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreGroup_ModifiedOn")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(250);
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}