// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnBReport.DAL.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Number { get; set; }

    public string Name { get; set; }

    public string GroupCode { get; set; }

    public string Unit { get; set; }

    public decimal? Cosprice { get; set; }

    public decimal? SellingPrice { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public virtual ProductGroup GroupCodeNavigation { get; set; }
}