// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnBReport.DAL.Models;

public partial class Store
{
    public int Id { get; set; }

    public string Number { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Nhom cac kho lai
    /// </summary>
    public int GroupId { get; set; }

    public decimal NumOfTables { get; set; }

    public decimal? MinMenuSelling { get; set; }

    public decimal? MinSalesContribution { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public virtual StoreGroup Group { get; set; }
}